In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_merged"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.oto_com` """
data_oto = client.query(query).to_dataframe()
data_oto.head(1)

,Name,Price,Năm_SX,Nhiên_liệu,Kiểu_dáng,Tình_trạng,Km_đã_đi,Hộp_số,Xuất_xứ,Tỉnh_thành,Số_tiền_vay,Thời_gian_vay,Lãi_xuất,Loại_hình,Giá_trị_xe_muốn_mua
0,Toyota Corolla Altis 2011,290 triệu,2011,Máy xăng,None,Xe cũ,100.000 km,Số tự động,Trong nước,Vĩnh Yên - Vĩnh Phúc,VNĐ,ThángNăm,ThángNăm,"Trả góp đều hàng thángTrả góp đều, lãi tính tr...",VNĐ

In [4]:
df_oto = data_oto.copy()

In [5]:
df_oto.columns

Index(['Name', 'Price', 'Năm_SX', 'Nhiên_liệu', 'Kiểu_dáng', 'Tình_trạng',
       'Km_đã_đi', 'Hộp_số', 'Xuất_xứ', 'Tỉnh_thành', 'Số_tiền_vay',
       'Thời_gian_vay', 'Lãi_xuất', 'Loại_hình', 'Giá_trị_xe_muốn_mua'],
      dtype='object')

In [6]:
df_oto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1482 entries, 0 to 1481
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 1481 non-null   object
 1   Price                1481 non-null   object
 2   Năm_SX               1481 non-null   object
 3   Nhiên_liệu           1481 non-null   object
 4   Kiểu_dáng            1384 non-null   object
 5   Tình_trạng           1481 non-null   object
 6   Km_đã_đi             1467 non-null   object
 7   Hộp_số               1480 non-null   object
 8   Xuất_xứ              1455 non-null   object
 9   Tỉnh_thành           1481 non-null   object
 10  Số_tiền_vay          1481 non-null   object
 11  Thời_gian_vay        1481 non-null   object
 12  Lãi_xuất             1481 non-null   object
 13  Loại_hình            1481 non-null   object
 14  Giá_trị_xe_muốn_mua  1481 non-null   object
dtypes: object(15)
memory usage: 173.8+ KB

In [7]:
df_oto = df_oto.rename(columns={
    "Nhiên_liệu": "fuel",
    "Kiểu_dáng": "body",
    "Km_đã_đi": "km",
    "Xuất_xứ": "origin",
    "Name": "name",
    "Price": "price",
    "Năm_SX": "year"
})

In [8]:
df_oto = df_oto[['fuel', 'body', 'km', 'origin', 'name','price', 'year','Tình_trạng']]

1.name

In [9]:
df_oto["name"] = df_oto["name"].apply(clean_name)
df_oto.head(5)

,fuel,body,km,origin,name,price,year,Tình_trạng
0,Máy xăng,None,100.000 km,Trong nước,Toyota Corolla Altis 2011,290 triệu,2011,Xe cũ
1,Máy xăng,None,80.000 km,Trong nước,Nissan Navara 2017,389 triệu,2017,Xe cũ
2,Máy xăng,None,69.000 km,Nhập khẩu,Toyota Camry 2017,585 triệu,2017,Xe cũ
3,Máy xăng,None,70.000 km,Trong nước,Nissan Navara 2018,430 triệu,2018,Xe cũ
4,Máy xăng,None,90.000 km,Trong nước,Nissan Navara 2019,429 triệu,2019,Xe cũ

2.price

In [10]:
df_oto["price"].isna().sum()

np.int64(1)

In [11]:
def clean_price(x):
    if pd.isna(x):
        return None
    
    x = str(x).lower().strip()

    if x in ["", "none", "nan", "giá liên hệ", "contact", "-"]:
        return None

    x = x.replace("triệu", "triệu").replace("trieuj", "triệu")
    x = x.replace("ty", "tỷ").replace("ti", "tỷ")

    x = x.replace("tỉ", "tỷ")

    x = re.sub(r"\s+", " ", x)

    if "triệu" not in x and "tỷ" not in x:
        digits = re.sub(r"[^\d]", "", x)
        return int(digits) if digits.isdigit() else None

    x = x.replace(",", ".")  

    match = re.match(r"(\d*\.?\d*)\s*tỷ\s*(\d*\.?\d*)?\s*triệu?", x)
    if match:
        ty = float(match.group(1)) if match.group(1) else 0
        trieu = float(match.group(2)) if match.group(2) else 0
        return int(ty * 1_000_000_000 + trieu * 1_000_000)

    if "tỷ" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000_000)
        return None

    if "triệu" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000)
        return None

    return None

In [12]:
df_oto["price"] = df_oto["price"].apply(clean_price)
df_oto.sample(5)

,fuel,body,km,origin,name,price,year,Tình_trạng
1429,Máy xăng,None,83.000 km,Trong nước,VinFast LUX SA2 0 2019,589000000.0,2019,Xe cũ
118,Máy xăng,Sedan,250.000 km,Nhập khẩu,Toyota Camry 2003,155000000.0,2003,Xe cũ
1393,Máy dầu,Bán tải,68.000 km,Trong nước,Ford Ranger 2021,670000000.0,2021,Xe cũ
1108,Máy xăng,SUV,50.000 km,Nhập khẩu,MG ZS 1 5 2WD STD 2022,390000000.0,2022,Xe cũ
114,Máy xăng,SUV,13.500 km,Nhập khẩu,Suzuki XL7 1 5L 2023,499000000.0,2023,Xe cũ

In [13]:
df_oto["price"].isna().sum()

np.int64(1)

In [14]:
df_oto = df_oto[df_oto["price"] > 50000000]

3.brand

In [15]:
df_oto["brand"] = df_oto["name"].str.strip().str.split().str[0]

In [16]:
df_oto.brand.value_counts()

brand
Toyota        271
Hyundai       159
Kia           154
Mercedes      150
Ford          117
Mazda          80
Mitsubishi     78
VinFast        74
Honda          72
Lexus          59
BMW            49
Porsche        30
Chevrolet      29
Suzuki         27
Audi           21
Nissan         20
MG             15
Peugeot        12
Volkswagen     10
Mini            8
Volvo           7
Land            5
Daewoo          4
Subaru          3
Bentley         3
Jaguar          3
Isuzu           3
Rolls           3
Dongben         2
Maserati        2
Acura           2
Smart           1
SRM             1
Teraco          1
KenBo           1
Hongqi          1
McLaren         1
Daihatsu        1
Name: count, dtype: int64

In [17]:
df_oto["brand"].isna().sum()

np.int64(0)

In [18]:
df_oto["brand"] = df_oto["brand"].str.lower()

4.year

In [19]:
df_oto["year"].head(5)

0    2011
1    2017
2    2017
3    2018
4    2019
Name: year, dtype: object

In [20]:
df_oto["age"] = 2026 - df_oto["year"].astype(int)
df_oto.drop(columns=["year"], inplace=True)
df_oto.head(1)

,fuel,body,km,origin,name,price,Tình_trạng,brand,age
0,Máy xăng,None,100.000 km,Trong nước,Toyota Corolla Altis 2011,290000000.0,Xe cũ,toyota,15

In [21]:
df_oto["age"].isna().sum()

np.int64(0)

5.status

In [22]:
df_oto["Tình_trạng"].unique()

array(['Xe cũ'], dtype=object)

In [23]:
df_oto.drop(columns=["Tình_trạng"], inplace=True)

6.km

In [24]:
df_oto["km"].head(5)

0    100.000 km
1     80.000 km
2     69.000 km
3     70.000 km
4     90.000 km
Name: km, dtype: object

In [25]:
df_oto["km"].isna().sum()

np.int64(14)

In [26]:
def cv_km(x):
    if pd.isna(x):        
        return None
    x = str(x).lower().strip()
    if x in ["", "-", "none"]:    
        return None
    x = (
        x.replace("km", "")
         .replace(".", "")
         .replace(",", "")
         .strip()
    )
    if x.isdigit():
        return int(x)
    return None

In [27]:
df_oto["km"] = df_oto["km"].apply(cv_km)

In [28]:
df_oto = df_oto[df_oto["km"] > 100]

In [29]:
df_oto["km"].isna().sum()

np.int64(0)

7.origin

In [30]:
df_oto["origin"].isna().sum()

np.int64(17)

In [31]:
df_oto["origin"].value_counts()

origin
Nhập khẩu     818
Trong nước    599
Name: count, dtype: int64

In [32]:
df_oto["origin"].describe()

count          1417
unique            2
top       Nhập khẩu
freq            818
Name: origin, dtype: object

In [33]:
df_oto["origin"] = df_oto["origin"].replace({
    "Trong nước": "trong nước",
    "Nhập khẩu": "nhập khẩu"
})

8.body

In [34]:
df_oto["body"].unique()

array([None, 'Bán tải', 'Convertible', 'Coupe', 'Crossover', 'Hatchback',
       'MPV', 'SUV', 'Sedan', 'Sport Car', 'Van/Minivan', 'Xe tải',
       'Minibus'], dtype=object)

In [35]:
df_oto["body"] = df_oto["body"].str.lower().str.strip()

In [36]:
df_oto["body"].isna().sum()

np.int64(92)

9.fuel

In [37]:
df_oto["fuel"].unique()

array(['Máy xăng', 'Máy dầu', 'Hybrid', 'Điện'], dtype=object)

In [38]:
df_oto["fuel"] = df_oto["fuel"].apply(clean_fuel)

In [39]:
df_oto["fuel"].unique()

array([None, 'Hybrid', 'Điện'], dtype=object)

In [40]:
df_oto["fuel"].isna().sum()

np.int64(1384)

In [41]:
df_oto["fuel"].value_counts()

fuel
Điện      37
Hybrid    13
Name: count, dtype: int64

10.updata

In [42]:
upload_to_bigquery(df_oto, table_id=table_id, if_exists="append" )

✅ Uploaded 1434 rows to khangtestdbt.xecupredict.data_merged

In [43]:
upload_to_db(df_oto,table_name)

✅ Saved 1434 rows to PostgreSQL table 'data_merged'

In [44]:
# end