In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_merged"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.bonbanh_com` """
data_bonbanh = client.query(query).to_dataframe()
data_bonbanh.head(1)

,Name,Năm_sản_xuất,Tình_trạng,Số_Km_đã_đi,Xuất_xứ,Kiểu_dáng,Hộp_số,Động_cơ,Màu_ngoại_thất,Màu_nội_thất,Dẫn_động
0,Xe \n\t\t\t\n\t\t\t\t\t\t\tHyundai i10 \n\t\t\...,2026,Xe đã dùng,200 Km,Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Đỏ,Đen,FWD - Dẫn động cầu trước

In [4]:
df_bonbanh = data_bonbanh.copy()

In [5]:
df_bonbanh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15990 entries, 0 to 15989
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            15990 non-null  object
 1   Năm_sản_xuất    15990 non-null  object
 2   Tình_trạng      15990 non-null  object
 3   Số_Km_đã_đi     11741 non-null  object
 4   Xuất_xứ         15990 non-null  object
 5   Kiểu_dáng       15990 non-null  object
 6   Hộp_số          15990 non-null  object
 7   Động_cơ         15990 non-null  object
 8   Màu_ngoại_thất  15990 non-null  object
 9   Màu_nội_thất    15990 non-null  object
 10  Dẫn_động        15990 non-null  object
dtypes: object(11)
memory usage: 1.3+ MB

In [6]:
df_bonbanh.isna().sum()

Name                 0
Năm_sản_xuất         0
Tình_trạng           0
Số_Km_đã_đi       4249
Xuất_xứ              0
Kiểu_dáng            0
Hộp_số               0
Động_cơ              0
Màu_ngoại_thất       0
Màu_nội_thất         0
Dẫn_động             0
dtype: int64

In [7]:
df_bonbanh.describe(include='all').T

,count,unique,top,freq
Name,15990,10562,Xe \n\t\t\t\n\t\t\t\t\t\t\tToyota Land Cruiser...,52
Năm_sản_xuất,15990,33,2026,2574
Tình_trạng,15990,2,Xe đã dùng,11741
Số_Km_đã_đi,11741,984,0 Km,1012
Xuất_xứ,15990,2,Lắp ráp trong nước,8532
Kiểu_dáng,15990,10,SUV,7854
Hộp_số,15990,2,Số tự động,14982
Động_cơ,15990,88,Xăng 2.0 L,3268
Màu_ngoại_thất,15990,18,Trắng,6031
Màu_nội_thất,15990,18,Đen,8122
Dẫn_động,15990,5,FWD - Dẫn động cầu trước,7537

In [8]:
df_bonbanh =df_bonbanh.drop(columns=['Màu_ngoại_thất','Màu_nội_thất','Dẫn_động'])

1.name

In [9]:
def clean_name(text):
    if not isinstance(text, str):
        return None
    
    text = re.sub(r"^\s*Xe\s+", "", text, flags=re.IGNORECASE)
    
    text = re.sub(r"[^a-zA-Z0-9À-ỹ\s]", " ", text)
    
    text = re.sub(r"\s+", " ", text)
    
    return text.strip()

In [10]:
df_bonbanh["name"] = df_bonbanh["Name"].apply(clean_name)
df_bonbanh.drop(columns=["Name"], inplace=True)
df_bonbanh.head(1)

,Năm_sản_xuất,Tình_trạng,Số_Km_đã_đi,Xuất_xứ,Kiểu_dáng,Hộp_số,Động_cơ,name
0,2026,Xe đã dùng,200 Km,Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT 2026 455 Triệu

2.price

In [11]:
def extract_price(name_str):
    if not isinstance(name_str, str):
        return None

    name_str = name_str.strip()
    
    match = re.search(r'(\d+(\.\d+)?\s*t[ỷi](?:\s*\d+\s*triệu)?)|(\d+(\.\d+)?\s*triệu)', name_str, re.IGNORECASE)
    if match:
        return match.group(0)
    return None

In [12]:
df_bonbanh['price'] = df_bonbanh['name'].apply(extract_price)
df_bonbanh.head(5)

,Năm_sản_xuất,Tình_trạng,Số_Km_đã_đi,Xuất_xứ,Kiểu_dáng,Hộp_số,Động_cơ,name,price
0,2026,Xe đã dùng,200 Km,Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT 2026 455 Triệu,455 Triệu
1,2022,Xe đã dùng,0 Km,Lắp ráp trong nước,Sedan,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT Tiêu Chuẩn 2022 335 Triệu,335 Triệu
2,2025,Xe đã dùng,"3,000 Km",Lắp ráp trong nước,Sedan,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT Tiêu Chuẩn 2025 386 Triệu,386 Triệu
3,2025,Xe đã dùng,"32,000 Km",Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT Tiêu Chuẩn 2025 385 Triệu,385 Triệu
4,2026,Xe mới,None,Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT Tiêu Chuẩn 2026 395 Triệu,395 Triệu

In [13]:
def clean_price(x):
    if pd.isna(x):
        return None
    
    x = str(x).lower().strip()

    if x in ["", "none", "nan", "giá liên hệ", "contact", "-"]:
        return None

    x = x.replace("triệu", "triệu").replace("trieuj", "triệu")
    x = x.replace("ty", "tỷ").replace("ti", "tỷ")

    x = x.replace("tỉ", "tỷ")

    x = re.sub(r"\s+", " ", x)

    if "triệu" not in x and "tỷ" not in x:
        digits = re.sub(r"[^\d]", "", x)
        return int(digits) if digits.isdigit() else None

    x = x.replace(",", ".")  

    match = re.match(r"(\d*\.?\d*)\s*tỷ\s*(\d*\.?\d*)?\s*triệu?", x)
    if match:
        ty = float(match.group(1)) if match.group(1) else 0
        trieu = float(match.group(2)) if match.group(2) else 0
        return int(ty * 1_000_000_000 + trieu * 1_000_000)

    if "tỷ" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000_000)
        return None

    if "triệu" in x:
        num = re.findall(r"[\d\.]+", x)
        if num:
            return int(float(num[0]) * 1_000_000)
        return None

    return None

In [14]:
df_bonbanh["price"] = df_bonbanh["price"].apply(clean_price)
df_bonbanh.head(2)

,Năm_sản_xuất,Tình_trạng,Số_Km_đã_đi,Xuất_xứ,Kiểu_dáng,Hộp_số,Động_cơ,name,price
0,2026,Xe đã dùng,200 Km,Lắp ráp trong nước,Hatchback,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT 2026 455 Triệu,455000000
1,2022,Xe đã dùng,0 Km,Lắp ráp trong nước,Sedan,Số tự động,Xăng 1.2 L,Hyundai i10 1 2 AT Tiêu Chuẩn 2022 335 Triệu,335000000

In [15]:
df_bonbanh["price"].isna().sum()

np.int64(0)

In [16]:
df_bonbanh = df_bonbanh[df_bonbanh["price"] > 50000000]

3.brand

In [17]:
df_bonbanh["brand"] = df_bonbanh["name"].str.strip().str.split().str[0]
df_bonbanh["brand"] = df_bonbanh["brand"].str.lower()

In [18]:
df_bonbanh["brand"].unique()

array(['hyundai', 'ford', 'gac', 'gaz', 'geely', 'haima', 'honda',
       'hongqi', 'haval', 'bmw', 'audi', 'baic', 'bentley', 'chevrolet',
       'chrysler', 'citroen', 'daewoo', 'daihatsu', 'dodge', 'dongben',
       'dongfeng', 'fiat', 'acura', 'aston', 'bestune', 'byd', 'cadillac',
       'kia', 'jeep', 'kenbo', 'lexus', 'mazda', 'lincoln', 'luxgen',
       'lynk', 'maserati', 'maybach', 'isuzu', 'jaecoo', 'jaguar',
       'infiniti', 'mercedes', 'mclaren', 'landrover', 'lamborghini',
       'subaru', 'suzuki', 'ram', 'renault', 'rolls', 'scion', 'skoda',
       'smart', 'ssangyong', 'porsche', 'toyota', 'sym', 'tank', 'thaco',
       'mitsubishi', 'mg', 'mini', 'morgan', 'nissan', 'peugeot', 'omoda',
       'vinfast', 'triumph', 'volkswagen', 'volvo', 'wuling', 'zotye'],
      dtype=object)

4.year

In [19]:
df_bonbanh["Năm_sản_xuất"].sample(5)

15512    2022
11167    2011
621      2025
1427     2008
1976     2019
Name: Năm_sản_xuất, dtype: object

In [20]:
df_bonbanh["Năm_sản_xuất"].isna().sum()
df_bonbanh["Năm_sản_xuất"] = df_bonbanh["Năm_sản_xuất"].astype("Int64")

In [21]:
df_bonbanh["age"] = 2026 - df_bonbanh["Năm_sản_xuất"]
df_bonbanh.drop(columns=["Năm_sản_xuất"], inplace=True)
df_bonbanh["age"].sample(5)

4482     8
4020     0
15950    1
14875    3
4031     0
Name: age, dtype: Int64

5.status

In [22]:
df_bonbanh["Tình_trạng"].unique()

array(['Xe đã dùng', 'Xe mới'], dtype=object)

In [23]:
df_bonbanh["Tình_trạng"].isna().sum()

np.int64(0)

In [24]:
df_bonbanh = df_bonbanh[df_bonbanh["Tình_trạng"] == "Xe đã dùng"]
df_bonbanh.drop(columns=["Tình_trạng"], inplace=True)

6.km

In [25]:
df_bonbanh["Số_Km_đã_đi"].sample(5)

141      180,000 Km
7915      80,000 Km
603       40,000 Km
12653     11,000 Km
4798      50,000 Km
Name: Số_Km_đã_đi, dtype: object

In [26]:
df_bonbanh["Số_Km_đã_đi"].isna().sum()

np.int64(0)

In [27]:
df_bonbanh.rename(columns={"Số_Km_đã_đi": "km"}, inplace=True)

In [28]:
df_bonbanh["km"] = pd.to_numeric(
    df_bonbanh["km"]
    .astype(str)                    
    .str.replace(r"[^\d]", "", regex=True),  
    errors="coerce"              
)

In [29]:
df_bonbanh["km"].isna().sum()

np.int64(0)

In [30]:
df_bonbanh["km"].sample(5)

11866     14560
11713       130
11753     50000
1773      39000
5069     120000
Name: km, dtype: int64

In [31]:
df_bonbanh = df_bonbanh[
    (df_bonbanh["km"] > 50) | (df_bonbanh["km"].isna())
]

In [32]:
df_bonbanh["km"].min()

np.int64(56)

7.origin

In [33]:
df_bonbanh["Xuất_xứ"].unique()

array(['Lắp ráp trong nước', 'Nhập khẩu'], dtype=object)

In [34]:
df_bonbanh = df_bonbanh.rename(columns={"Xuất_xứ": "origin"})

In [35]:
df_bonbanh["origin"] = df_bonbanh["origin"].replace({
    "Lắp ráp trong nước": "trong nước",
    "Nhập khẩu": "nhập khẩu"
})

In [36]:
df_bonbanh["origin"].isna().sum()

np.int64(0)

In [37]:
df_bonbanh["origin"].value_counts()

origin
trong nước    5610
nhập khẩu     4974
Name: count, dtype: int64

8.body

In [38]:
df_bonbanh["Kiểu_dáng"].unique()

array(['Hatchback', 'Sedan', 'Van/Minivan', 'SUV', 'Truck', 'Crossover',
       'Coupe', 'Bán tải / Pickup', 'Convertible/Cabriolet', 'Wagon'],
      dtype=object)

In [39]:
df_bonbanh = df_bonbanh.rename(columns={"Kiểu_dáng": "body"})
df_bonbanh["body"] = df_bonbanh["body"].str.lower().str.strip()

In [40]:
df_bonbanh["body"].isna().sum()

np.int64(0)

In [41]:
df_bonbanh["body"].value_counts()

body
suv                      4967
sedan                    2632
crossover                 890
van/minivan               737
hatchback                 617
bán tải / pickup        546
coupe                      99
convertible/cabriolet      71
truck                      24
wagon                       1
Name: count, dtype: int64

9.fuel

In [42]:
df_bonbanh["Động_cơ"].unique()

array(['Xăng  1.2 L', 'Xăng  1.0 L', 'Xăng  1.25 L', 'Xăng  1.4 L',
       'Xăng  1.6 L', 'Dầu', 'Xăng  1.5 L', 'Dầu  2.2 L', 'Xăng  2.4 L',
       'Xăng  2.5 L', 'Xăng  2.0 L', 'Dầu  2.0 L', 'Xăng  2.7 L',
       'Xăng  4.6 L', 'Xăng  3.3 L', 'Xăng  3.8 L', 'Xăng  1.1 L',
       'Dầu  2.5 L', 'Xăng  3.5 L', 'Dầu  3.9 L', 'Xăng  1.8 L',
       'Dầu  2.4 L', 'Dầu  2.3 L', 'Dầu  2.8 L', 'Điện', 'Hybrid  2.0 L',
       'Xăng', 'Hybrid  1.5 L', 'Xăng  2.3 L', 'Xăng  4.0 L',
       'Xăng  3.0 L', 'Xăng  2.6 L', 'Xăng  5.0 L', 'Hybrid  3.0 L',
       'Xăng  4.2 L', 'Xăng  5.2 L', 'Xăng  6.0 L', 'Dầu  3.0 L',
       'Xăng  4.4 L', 'Xăng  1.3 L', 'Xăng  3.6 L', 'Xăng  0.9 L',
       'Xăng  3.7 L', 'Xăng  5.9 L', 'Xăng  6.8 L', 'Xăng  6.2 L',
       'Xăng  0.8 L', 'Dầu  3.2 L', 'Hybrid  1.6 L', 'Dầu  1.5 L',
       'Xăng  5.7 L', 'Xăng  3.4 L', 'Hybrid  2.5 L', 'Hybrid  3.5 L',
       'Hybrid  2.4 L', 'Hybrid  5.0 L', 'Xăng  4.7 L', 'Dầu  1.9 L',
       'Dầu  5.2 L', 'Xăng  3.2 L', 'Xăng  5.6 L', 'Xăng  4.3 L',
       'Xăng  6.5 L', 'Xăng  6.7 L', 'Xăng  6.6 L', 'Dầu  2.7 L',
       'Xăng  2.9 L', 'Xăng  4.8 L', 'Điện  0.7 L', 'Điện  0.9 L',
       'Điện  0.4 L', 'Xăng  5.5 L', 'Dầu  2.1 L', 'Hybrid',
       'Hybrid  1.2 L', 'Xăng  2.2 L', 'Hybrid  1.8 L', 'Xăng  4.5 L',
       'Dầu  3.4 L', 'Điện  0.6 L'], dtype=object)

In [43]:
df_bonbanh = df_bonbanh.rename(columns={"Động_cơ": "fuel"})
df_bonbanh["fuel"] = df_bonbanh["fuel"].apply(clean_fuel)

In [44]:
df_bonbanh["fuel"].isna().sum()

np.int64(0)

In [45]:
df_bonbanh["fuel"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Hybrid'], dtype=object)

In [46]:
df_bonbanh["fuel"].value_counts()

fuel
Xăng      8144
Dầu       1752
Điện       433
Hybrid     255
Name: count, dtype: int64

In [47]:
df_bonbanh = df_bonbanh[df_bonbanh["fuel"] != "Khác"]

10.gearbox

In [48]:
df_bonbanh.rename(columns={"Hộp_số": "gearbox"}, inplace=True)

In [49]:
df_bonbanh['gearbox'].isna().sum()

np.int64(0)

In [50]:
df_bonbanh['gearbox'].unique()

array(['Số tự động', 'Số tay'], dtype=object)

In [51]:
df_bonbanh["gearbox"] = df_bonbanh["gearbox"].replace({
    "Số tay": "Số sàn"
})

In [52]:
df_bonbanh.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10584 entries, 0 to 15987
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   km       10584 non-null  int64
 1   origin   10584 non-null  object
 2   body     10584 non-null  object
 3   gearbox  10584 non-null  object
 4   fuel     10584 non-null  object
 5   name     10584 non-null  object
 6   price    10584 non-null  int64
 7   brand    10584 non-null  object
 8   age      10584 non-null  Int64
dtypes: Int64(1), int64(2), object(6)
memory usage: 837.2+ KB

11.updata

In [53]:
df_bonbanh.sample(10)

,km,origin,body,gearbox,fuel,name,price,brand,age
10967,12000,nhập khẩu,hatchback,Số tự động,Xăng,Mini One 1 5 AT 2022 1 Tỷ 450 Triệu,1450000000,mini,4
6807,20000,trong nước,suv,Số tự động,Xăng,Hyundai Venue 1 0 T GDi Đặc Biệt 2024 520 Triệu,520000000,hyundai,2
3384,63000,nhập khẩu,sedan,Số tự động,Xăng,BMW 3 Series 320i 2018 699 Triệu,699000000,bmw,8
5361,32503,nhập khẩu,suv,Số tự động,Xăng,Lexus RX 350 Premium 2023 3 Tỷ 180 Triệu,3180000000,lexus,3
344,33000,trong nước,suv,Số tự động,Xăng,Hyundai SantaFe Cao cấp 2 5L HTRAC 2022 1 Tỷ 6...,1060000000,hyundai,4
11800,100000,nhập khẩu,bán tải / pickup,Số tự động,Dầu,Nissan Navara EL Premium R 2017 415 Triệu,415000000,nissan,9
9761,40000,nhập khẩu,suv,Số tự động,Xăng,Mercedes Benz G class G63 AMG 2021 7 Tỷ 400 Triệu,7400000000,mercedes,5
3072,50000,trong nước,suv,Số tự động,Xăng,Ford EcoSport Titanium 1 0 EcoBoost 2018 415 T...,415000000,ford,8
13721,100000,nhập khẩu,suv,Số tự động,Xăng,Toyota Prado VX 2 7L 2018 1 Tỷ 888 Triệu,1888000000,toyota,8
9757,40000,nhập khẩu,suv,Số tự động,Xăng,Mercedes Benz G class G63 AMG 2021 7 Tỷ 500 Triệu,7500000000,mercedes,5

In [54]:
upload_to_bigquery(df_bonbanh, table_id=table_id, if_exists="replace" )

✅ Uploaded 10584 rows to khangtestdbt.xecupredict.data_merged

In [55]:
upload_to_db(df_bonbanh,table_name)

✅ Saved 10584 rows to PostgreSQL table 'data_merged'

In [56]:
# end