In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_cleaned"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.data_merged` """
data_merged = client.query(query).to_dataframe()
data_merged.head(1)

,km,origin,body,fuel,name,price,brand,age
0,100000,trong nước,None,None,Toyota Corolla Altis 2011,290000000.0,toyota,15

In [4]:
df = data_merged.copy()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15688 entries, 0 to 15687
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   km      15688 non-null  Int64
 1   origin  15671 non-null  object
 2   body    13340 non-null  object
 3   fuel    14304 non-null  object
 4   name    15688 non-null  object
 5   price   15688 non-null  float64
 6   brand   15688 non-null  object
 7   age     15688 non-null  Int64
dtypes: Int64(2), float64(1), object(5)
memory usage: 1011.3+ KB

In [6]:
df.duplicated().sum()

np.int64(632)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.isna().sum()

km           0
origin      17
body      2341
fuel      1342
name         0
price        0
brand        0
age          0
dtype: int64

1.brand

In [9]:
df["brand"].dtype

dtype('O')

In [10]:
df["brand"].unique()

array(['toyota', 'nissan', 'porsche', 'suzuki', 'smart', 'mitsubishi',
       'peugeot', 'subaru', 'rolls', 'srm', 'teraco', 'vinfast', 'ford',
       'hyundai', 'honda', 'hongqi', 'kia', 'isuzu', 'jaguar', 'kenbo',
       'lexus', 'mercedes', 'mazda', 'mclaren', 'land', 'maserati', 'mg',
       'mini', 'acura', 'audi', 'bentley', 'bmw', 'chevrolet', 'daewoo',
       'daihatsu', 'dongben', 'volkswagen', 'volvo', 'ram', 'renault',
       'scion', 'omoda', 'ssangyong', 'landrover', 'lamborghini', 'gaz',
       'cadillac', 'citroen', 'dodge', 'ferrari', 'fiat', 'aston', 'baic',
       'jeep', 'infiniti', 'sym', 'thaco', 'wuling', 'byd', 'lynk&co',
       'mercedes benz', 'hãng khác', 'chery', 'uaz', 'zotye', 'haima',
       'samsung', 'gmc', 'luxgen', 'rolls royce', 'changan', 'geely',
       'chrysler', 'dongfeng', 'hummer', 'proton'], dtype=object)

In [11]:
brand_alias = {
    "mercedes": "mercedes-benz",
    "mercedes benz": "mercedes-benz",

    "rolls": "rolls-royce",
    "rolls royce": "rolls-royce",

    "land": "land rover",
    "landrover": "land rover",

    "lynk": "lynk & co",
    "lynk&co": "lynk & co",
}

In [12]:
df["brand"] = df["brand"].replace(brand_alias)

top_brands = df["brand"].value_counts().nlargest(25).index
df["brand"] = df["brand"].apply(lambda x: x if x in top_brands else "other")

In [13]:
df["brand"].value_counts()

brand
toyota           2710
ford             1539
kia              1500
mercedes-benz    1440
hyundai          1375
mazda             874
vinfast           835
mitsubishi        799
honda             607
lexus             542
bmw               460
chevrolet         340
other             251
suzuki            245
porsche           240
audi              197
peugeot           187
nissan            169
land rover        167
mg                151
volkswagen        114
volvo              88
isuzu              77
daewoo             64
mini               48
subaru             37
Name: count, dtype: int64

2.origin

In [14]:
df["origin"].unique()

array(['trong nước', 'nhập khẩu', None], dtype=object)

In [15]:
df["origin"].value_counts()

origin
nhập khẩu     8760
trong nước    6279
Name: count, dtype: int64

In [16]:
origin_mode_per_brand = df.groupby('brand')['origin'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
origin_mode_per_brand

brand
audi              nhập khẩu
bmw               nhập khẩu
chevrolet         nhập khẩu
daewoo            nhập khẩu
ford              nhập khẩu
honda             nhập khẩu
hyundai          trong nước
isuzu             nhập khẩu
kia              trong nước
land rover        nhập khẩu
lexus             nhập khẩu
mazda            trong nước
mercedes-benz    trong nước
mg                nhập khẩu
mini              nhập khẩu
mitsubishi        nhập khẩu
nissan            nhập khẩu
other             nhập khẩu
peugeot          trong nước
porsche           nhập khẩu
subaru            nhập khẩu
suzuki            nhập khẩu
toyota            nhập khẩu
vinfast          trong nước
volkswagen        nhập khẩu
volvo             nhập khẩu
Name: origin, dtype: object

In [17]:
df['origin'] = df.apply(
    lambda row: origin_mode_per_brand[row['brand']] if pd.isna(row['origin']) else row['origin'],
    axis=1
)

In [18]:
df['origin'].isna().sum()

np.int64(0)

3.body

In [19]:
df["body"].unique()

array([None, 'bán tải', 'convertible', 'coupe', 'crossover', 'hatchback',
       'mpv', 'suv', 'sedan', 'sport car', 'van/minivan', 'xe tải',
       'minibus', 'wagon', 'bán tải / pickup', 'convertible/cabriolet',
       'truck', 'suv / cross over', 'minivan (mpv)', 'pick-up (bán tải)',
       'van', 'kiểu dáng khác', 'coupe (2 cửa)', 'mui trần'], dtype=object)

In [20]:
df['body'] = df['body'].replace({
    'xe tải': 'truck',
    'truck': 'truck',
    'bán tải': 'pickup',
    'bán tải / pickup': 'pickup',
    'pick-up (bán tải)': 'pickup',
    'van/minivan': 'minivan',
    'minivan (mpv)': 'minivan',
    'mpv': 'minivan',
    'suv / cross over': 'suv',
    'crossover': 'suv',
    'convertible/cabriolet': 'convertible',
    'coupe (2 cửa)': 'coupe'
})

In [21]:
body_mode_per_brand = df.groupby('brand')['body'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
body_mode_per_brand

brand
audi                   suv
bmw                  sedan
chevrolet            sedan
daewoo               sedan
ford                   suv
honda                  suv
hyundai                suv
isuzu                  suv
kia                minivan
land rover             suv
lexus                  suv
mazda                  suv
mercedes-benz        sedan
mg                   sedan
mini             hatchback
mitsubishi             suv
nissan              pickup
other                sedan
peugeot                suv
porsche                suv
subaru                 suv
suzuki           hatchback
toyota                 suv
vinfast                suv
volkswagen             suv
volvo                  suv
Name: body, dtype: object

In [22]:
df['body'] = df.apply(
    lambda row: body_mode_per_brand[row['brand']] if pd.isna(row['body']) else row['body'],
    axis=1
)

In [23]:
df['body'].isna().sum()

np.int64(0)

4.fuel

In [24]:
df["fuel"].unique()

array([None, 'Hybrid', 'Điện', 'Xăng', 'Dầu'], dtype=object)

In [25]:
df['fuel'] = df['fuel'].str.lower()

In [26]:
fuel_mode_per_brand_body = df.groupby(["brand","body"])['fuel'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
def fill_fuel(row):
    if pd.isna(row['fuel']):
        return fuel_mode_per_brand_body.get((row['brand'], row['body']), None)
    else:
        return row['fuel']

df['fuel'] = df.apply(fill_fuel, axis=1)

In [27]:
df['fuel'].isna().sum()

np.int64(9)

In [28]:
fuel_mode_per_brand = df.groupby('brand')['fuel'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
df['fuel'] = df.apply(
    lambda row: fuel_mode_per_brand[row['brand']] if pd.isna(row['fuel']) else row['fuel'],
    axis=1
)

df['fuel'].isna().sum()

np.int64(0)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15056 entries, 0 to 15687
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   km      15056 non-null  Int64
 1   origin  15056 non-null  object
 2   body    15056 non-null  object
 3   fuel    15056 non-null  object
 4   name    15056 non-null  object
 5   price   15056 non-null  float64
 6   brand   15056 non-null  object
 7   age     15056 non-null  Int64
dtypes: Int64(2), float64(1), object(5)
memory usage: 1.1+ MB

5.outlier

In [30]:
df["price"] = df["price"].astype(float)
df["km"] = df["km"].astype(float)
df["age"] = df["age"].astype(float)

In [31]:
def cap_outliers_group(df, column, group_cols):
    def cap_group(x):
        Q1 = x[column].quantile(0.25)
        Q3 = x[column].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        return x[column].clip(lower, upper)
    
    df[column] = df.groupby(group_cols, group_keys=False).apply(cap_group)
    return df

In [32]:
df = cap_outliers_group(df, "km", ['age'])
df = cap_outliers_group(df, "price", ['brand','age'])

In [33]:
df.head()

,km,origin,body,fuel,name,price,brand,age
0,100000.0,trong nước,suv,xăng,Toyota Corolla Altis 2011,290000000.0,toyota,15.0
1,80000.0,trong nước,pickup,dầu,Nissan Navara 2017,389000000.0,nissan,9.0
2,69000.0,nhập khẩu,suv,xăng,Toyota Camry 2017,585000000.0,toyota,9.0
3,70000.0,trong nước,pickup,dầu,Nissan Navara 2018,430000000.0,nissan,8.0
4,90000.0,trong nước,pickup,dầu,Nissan Navara 2019,429000000.0,nissan,7.0

In [34]:
df.drop(columns=["name"], inplace=True)

In [35]:
X = df.drop(columns=["price"])
X.head()

         km      origin    body  fuel   brand   age
0  100000.0  trong nước     suv  xăng  toyota  15.0
1   80000.0  trong nước  pickup   dầu  nissan   9.0
2   69000.0   nhập khẩu     suv  xăng  toyota   9.0
3   70000.0  trong nước  pickup   dầu  nissan   8.0
4   90000.0  trong nước  pickup   dầu  nissan   7.0

In [36]:
X[X.duplicated(keep=False)]

             km      origin   body  fuel    brand   age
2       69000.0   nhập khẩu    suv  xăng   toyota   9.0
5       86000.0  trong nước    suv  xăng   toyota   7.0
6       30000.0   nhập khẩu    suv  xăng  porsche   5.0
9       42000.0   nhập khẩu    suv  xăng   toyota   4.0
10       8000.0   nhập khẩu    suv  xăng  porsche   3.0
...         ...         ...    ...   ...      ...   ...
15661  123456.0   nhập khẩu  sedan  xăng   toyota  33.0
15667  123456.0   nhập khẩu  sedan  xăng   toyota  33.0
15669  123456.0   nhập khẩu  sedan  xăng   toyota  33.0
15682  686868.0   nhập khẩu    suv   dầu   toyota  36.0
15683  686868.0   nhập khẩu    suv   dầu   toyota  36.0

[6249 rows x 6 columns]

In [37]:
df_unique = df.groupby(list(X.columns), as_index=False)["price"].mean()
df_unique

,km,origin,body,fuel,brand,age,price
0,55.0,nhập khẩu,sedan,xăng,bmw,20.0,165000000.0
1,55.0,trong nước,suv,điện,vinfast,1.0,265000000.0
2,56.0,trong nước,suv,điện,vinfast,2.0,740000000.0
3,60.0,nhập khẩu,sedan,xăng,kia,7.0,315000000.0
4,60.0,nhập khẩu,sedan,xăng,mitsubishi,4.0,445000000.0
...,...,...,...,...,...,...,...
11156,395000.0,trong nước,sedan,xăng,toyota,25.0,148000000.0
11157,443830.0,nhập khẩu,kiểu dáng khác,xăng,mitsubishi,29.0,80000000.0
11158,450000.0,nhập khẩu,sedan,xăng,toyota,31.0,75000000.0
11159,456321.0,nhập khẩu,suv,xăng,isuzu,29.0,79000000.0
11160,686868.0,nhập khẩu,suv,dầu,toyota,36.0,352500000.0

In [38]:
cols_show = ["brand", "body", "fuel", "origin"]

df_unique[cols_show] = df_unique[cols_show].apply(lambda c: c.str.title())

In [39]:
df_unique.sample(10)

,km,origin,body,fuel,brand,age,price
7193,81000.0,Nhập Khẩu,Suv,Xăng,Hyundai,7.0,3.455000e+08
10672,174000.0,Trong Nước,Suv,Xăng,Ford,21.0,1.150000e+08
2494,28000.0,Nhập Khẩu,Hatchback,Xăng,Ford,8.0,3.260000e+08
1543,15000.0,Trong Nước,Minivan,Dầu,Ford,1.0,1.500000e+09
10417,155000.0,Nhập Khẩu,Suv,Xăng,Audi,18.0,2.880000e+08
7718,90000.0,Nhập Khẩu,Hatchback,Xăng,Chevrolet,11.0,1.750000e+08
6856,79000.0,Trong Nước,Sedan,Xăng,Mercedes-Benz,8.0,7.480000e+08
3775,42939.0,Nhập Khẩu,Suv,Xăng,Hyundai,7.0,3.250000e+08
318,1900.0,Trong Nước,Sedan,Xăng,Mazda,1.0,6.480000e+08
7754,90000.0,Nhập Khẩu,Pickup,Dầu,Nissan,11.0,3.790000e+08

In [40]:
df_unique.duplicated().sum()

np.int64(0)

In [41]:
import json


unique_values = {
    'origin': df_unique['origin'].value_counts().index.tolist(),
    'fuel':   df_unique['fuel'].value_counts().index.tolist(),
    'body':   df_unique['body'].value_counts().index.tolist(),
    'brand':  df_unique['brand'].value_counts().index.tolist(),
}

with open('../../model/unique_values.json', 'w', encoding='utf-8') as f:
    json.dump(unique_values, f, ensure_ascii=False, indent=2)

In [42]:
upload_to_bigquery(df_unique, table_id=table_id, if_exists="replace" )

✅ Uploaded 11161 rows to khangtestdbt.xecupredict.data_cleaned

In [43]:
upload_to_db(df_unique,table_name)

✅ Saved 11161 rows to PostgreSQL table 'data_cleaned'

# end