In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_merged"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.chotot_com` """
data_chotot = client.query(query).to_dataframe()
data_chotot.head(1)

,name,price,Số_Km_đã_đi,Xuất_xứ,Tình_trạng,Chính_sách_bảo_hành,Hãng,Dòng_xe,Năm_sản_xuất,Hộp_số,Nhiên_liệu,Trọng_lượng,Trọng_tải,Kiểu_dáng,Số_chỗ,Số_đời_chủ,Có_phụ_kiện_đi_kèm,Còn_hạn_đăng_kiểm
0,BMW 3 Series 2013 FULL OPTION TIỀN DỌN HƠN 200TR,550.000.000 đ,50000,Đức,Đã sử dụng,Bảo hành hãng,BMW,3 Series,2013,Tự động,Xăng,> 1 tấn,> 2 tấn,None,None,None,None,None

In [4]:
df_chotot = data_chotot.copy()

In [5]:
df_chotot.columns

Index(['name', 'price', 'Số_Km_đã_đi', 'Xuất_xứ', 'Tình_trạng',
       'Chính_sách_bảo_hành', 'Hãng', 'Dòng_xe', 'Năm_sản_xuất', 'Hộp_số',
       'Nhiên_liệu', 'Trọng_lượng', 'Trọng_tải', 'Kiểu_dáng', 'Số_chỗ',
       'Số_đời_chủ', 'Có_phụ_kiện_đi_kèm', 'Còn_hạn_đăng_kiểm'],
      dtype='object')

In [6]:
df_chotot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8829 entries, 0 to 8828
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 8829 non-null   object
 1   price                8829 non-null   object
 2   Số_Km_đã_đi          7910 non-null   object
 3   Xuất_xứ              8829 non-null   object
 4   Tình_trạng           8829 non-null   object
 5   Chính_sách_bảo_hành  8829 non-null   object
 6   Hãng                 8829 non-null   object
 7   Dòng_xe              8829 non-null   object
 8   Năm_sản_xuất         8829 non-null   object
 9   Hộp_số               8829 non-null   object
 10  Nhiên_liệu           8829 non-null   object
 11  Trọng_lượng          8002 non-null   object
 12  Trọng_tải            8002 non-null   object
 13  Kiểu_dáng            6156 non-null   object
 14  Số_chỗ               7336 non-null   object
 15  Số_đời_chủ           3905 non-null   object
 16  Có_phụ_kiện_đi_kèm   3712 non-null   object
 17  Còn_hạn_đăng_kiểm    4029 non-null   object
dtypes: object(18)
memory usage: 1.2+ MB

In [7]:
df_chotot = df_chotot[["Số_Km_đã_đi", "Tình_trạng", "Xuất_xứ", "Kiểu_dáng", "Nhiên_liệu", "name", "price", "Hãng", "Năm_sản_xuất"]].copy()

In [8]:
df_chotot.columns = ["km", "Tình_trạng", "origin", "body", "fuel", "name", "price", "brand", "age"]

In [9]:
df_chotot.describe(include='all').T

           count unique               top  freq
km          7910   1236            100000   276
Tình_trạng  8829      2        Đã sử dụng  8002
origin      8829     11          Việt Nam  3125
body        6156      9  SUV / Cross over  2424
fuel        8829      4              Xăng  6660
name        8829   8612            Bán xe     6
price       8829   1252     315.000.000 đ    57
brand       8829     61            Toyota  1773
age         8829     45              2022   915

In [10]:
df_chotot.isna().sum()

km             919
Tình_trạng       0
origin           0
body          2673
fuel             0
name             0
price            0
brand            0
age              0
dtype: int64

1.name

In [11]:
df_chotot["name"] = df_chotot["name"].apply(clean_name)
df_chotot.head(1)

,km,Tình_trạng,origin,body,fuel,name,price,brand,age
0,50000,Đã sử dụng,Đức,None,Xăng,BMW 3 Series 2013 FULL OPTION TIỀN DỌN HƠN 200TR,550.000.000 đ,BMW,2013

2.price

In [12]:
df_chotot["price"].sample(5)

4556    340.000.000 đ
8524    619.000.000 đ
2683    185.000.000 đ
6527     85.000.000 đ
2786    535.000.000 đ
Name: price, dtype: object

In [13]:
df_chotot["price"] = (
    df_chotot["price"]
    .str.replace("đ", "", regex=False)
    .str.replace(".", "", regex=False)
    .str.strip()
    .astype(float)
    .astype("Int64")
)
df_chotot.price.sample(5)

4573     319000000
6026     799000000
5166    1479000000
8290     449000000
982      675000000
Name: price, dtype: Int64

In [14]:
df_chotot["price"].isna().sum()

np.int64(0)

In [15]:
df_chotot = df_chotot[df_chotot["price"] > 50000000]

3.brand

In [16]:
df_chotot["brand"].sample(5)

1070        Kia
6875      Mazda
4245       Ford
5719     Toyota
7763    Peugeot
Name: brand, dtype: object

In [17]:
df_chotot["brand"].isna().sum()

np.int64(0)

In [18]:
df_chotot["brand"].unique()

array(['BMW', 'Toyota', 'Mitsubishi', 'Mazda', 'Chevrolet', 'Daewoo',
       'Ford', 'Honda', 'Hyundai', 'Isuzu', 'Kia', 'Lexus',
       'Mercedes Benz', 'Suzuki', 'VinFast', 'Daihatsu', 'Hãng khác',
       'MG', 'Volkswagen', 'Audi', 'Nissan', 'Smart', 'Acura',
       'Ssangyong', 'LandRover', 'BYD', 'Geely', 'Wuling', 'MINI',
       'Skoda', 'Porsche', 'Peugeot', 'Chery', 'Gaz', 'UAZ', 'Subaru',
       'Lynk&Co', 'GAC', 'Volvo', 'Fiat', 'Infiniti', 'Chrysler', 'Jeep',
       'Jaguar', 'Cadillac', 'Rolls Royce', 'HongQi', 'Zotye', 'Maserati',
       'Luxgen', 'Changan', 'Samsung', 'Haima', 'Baic', 'GMC', 'Proton',
       'Hummer', 'Ferrari', 'Citroen', 'Dongfeng'], dtype=object)

In [19]:
df_chotot["brand"] = df_chotot["brand"].str.lower()

4.year

In [20]:
df_chotot["age"].isna().sum()

np.int64(0)

In [21]:
df_chotot["age"] = pd.to_numeric(df_chotot["age"], errors="coerce")

In [22]:
df_chotot = df_chotot.dropna(subset=["age"])

In [23]:
df_chotot["age"] = 2026 - df_chotot["age"].astype(int)

In [24]:
df_chotot.sample(5)

,km,Tình_trạng,origin,body,fuel,name,price,brand,age
6525,85000,Đã sử dụng,Hàn Quốc,None,Dầu,Cần bán Karado số tự đ 2004 máy dầu 2 cầu,55000000,ssangyong,22
6244,120000,Đã sử dụng,Đang cập nhật,SUV / Cross over,Xăng,Lexus GX460 2009,1150000000,lexus,17
2897,43000,Đã sử dụng,Đang cập nhật,None,Xăng,Mazda 3 Sport Premium 2020 Trắng,580000000,mazda,6
4142,51000,Đã sử dụng,Thái Lan,Pick-up (bán tải),Dầu,Ford Ranger 2023 Raptor 2 0L 4x4 AT 51000 km,1115000000,ford,3
2625,47000,Đã sử dụng,Nhật Bản,SUV / Cross over,Dầu,nha ich su dung mua di lien,840000000,hãng khác,6

In [25]:
df_chotot["age"].isna().sum()

np.int64(0)

5.status

In [26]:
df_chotot["Tình_trạng"].unique()

array(['Đã sử dụng', 'Mới'], dtype=object)

In [27]:
df_chotot = df_chotot[df_chotot["Tình_trạng"] == "Đã sử dụng"]
df_chotot.drop(columns=["Tình_trạng"], inplace=True)

6.km

In [28]:
df_chotot["km"].head(5)

0     50000
1       100
2    125402
3    163556
4       150
Name: km, dtype: object

In [29]:
df_chotot["km"].isna().sum()

np.int64(87)

In [30]:
df_chotot["km"].describe()

count       7698
unique      1217
top       100000
freq         252
Name: km, dtype: object

In [31]:
df_chotot["km"] = pd.to_numeric(df_chotot["km"], errors="coerce").fillna(0).astype(int)

In [32]:
df_chotot = df_chotot[df_chotot["km"] > 50]

In [33]:
df_chotot.head()

,km,origin,body,fuel,name,price,brand,age
0,50000,Đức,None,Xăng,BMW 3 Series 2013 FULL OPTION TIỀN DỌN HƠN 200TR,550000000,bmw,13
1,100,Đang cập nhật,None,Xăng,BMW 318i Đen Số tự động,86000000,bmw,22
2,125402,Đang cập nhật,None,Xăng,BMW 745Li màu Đỏ,186000000,bmw,19
3,163556,Nước khác,None,Xăng,BÁN XE Toyota Innova 2 0G 2019 Chính chủ bán,565000000,toyota,7
4,150,Nhật Bản,None,Xăng,Bán Mitsubishi Jolie S 2006 hoặc đổi xe nhỏ hơn,68000000,mitsubishi,20

7.origin

In [34]:
df_chotot["origin"].unique()

array(['Đức', 'Đang cập nhật', 'Nước khác', 'Nhật Bản', 'Việt Nam',
       'Thái Lan', 'Hàn Quốc', 'Mỹ', 'Ấn Độ', 'Trung Quốc', 'Đài Loan'],
      dtype=object)

In [35]:
df_chotot["origin"] = df_chotot["origin"].replace({
    "Việt Nam": "trong nước"
}).apply(lambda x: "nhập khẩu" if x not in ["trong nước"] else x)

In [36]:
df_chotot["origin"].value_counts()

origin
nhập khẩu     5007
trong nước    2527
Name: count, dtype: int64

8.body

In [37]:
df_chotot["body"].isna().sum()

np.int64(2256)

In [38]:
df_chotot["body"].unique()

array([None, 'Hatchback', 'Kiểu dáng khác', 'Minivan (MPV)',
       'Pick-up (bán tải)', 'SUV / Cross over', 'Sedan', 'Van',
       'Coupe (2 cửa)', 'Mui trần'], dtype=object)

In [39]:
df_chotot["body"] = df_chotot["body"].str.lower().str.strip()

9.fuel

In [40]:
df_chotot["fuel"].isna().sum()

np.int64(0)

In [41]:
df_chotot["fuel"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Động cơ Hybrid'], dtype=object)

In [42]:
df_chotot["fuel"] = df_chotot["fuel"].apply(clean_fuel)

In [43]:
df_chotot["fuel"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Hybrid'], dtype=object)

10.updata

In [44]:
df_chotot.sample(10)

,km,origin,body,fuel,name,price,brand,age
8776,116000,nhập khẩu,sedan,Xăng,Chevrolet Cruze LT 2017 Trắng,242000000,chevrolet,9
6413,55000,nhập khẩu,pick-up (bán tải),Dầu,FORD RANGER XLS AT đklđ 2020 một chủ mua mới,505000000,ford,4
270,100000,nhập khẩu,None,Xăng,Lexus LS 400 màu Đen,90000000,lexus,25
5735,89800,nhập khẩu,suv / cross over,Xăng,Mercedes Benz GL Class 2008 89800 km,285000000,mercedes benz,18
3222,10000,nhập khẩu,None,Dầu,Stazex van 6 chỗ máy dầu,395000000,hyundai,10
6745,800000,trong nước,suv / cross over,Xăng,Peugeot 3008 2021 Trắng 95 mới,720000000,peugeot,5
2699,113000,nhập khẩu,minivan (mpv),Xăng,Toyota Avanza 2019 Tự động Xám,348000000,toyota,7
4535,38000,trong nước,suv / cross over,Xăng,Kia Sonet 2022 Premium 1 5AT Đỏ,516000000,kia,4
5680,39000,nhập khẩu,None,Xăng,MG5 Luxury 2022 chính chủ sử dụng 39 ngàn km,370000000,mg,4
4630,57000,nhập khẩu,hatchback,Xăng,Mazda 3 Sport 2019 Luxury Trắng,445000000,mazda,7

In [45]:
upload_to_bigquery(df_chotot, table_id=table_id, if_exists="append" )

✅ Uploaded 7534 rows to khangtestdbt.xecupredict.data_merged

In [46]:
upload_to_db(df_chotot,table_name)

✅ Saved 7534 rows to PostgreSQL table 'data_merged'

In [47]:
#end