In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_merged"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.chotot_com` """
data_chotot = client.query(query).to_dataframe()
data_chotot.head(1)

,name,price,Số_Km_đã_đi,Xuất_xứ,Tình_trạng,Chính_sách_bảo_hành,Hãng,Dòng_xe,Năm_sản_xuất,Hộp_số,Nhiên_liệu,Trọng_lượng,Trọng_tải,Số_đời_chủ,Có_phụ_kiện_đi_kèm,Còn_hạn_đăng_kiểm,Số_chỗ,Kiểu_dáng
0,xe Vinfast bao nợ xấu,5.000.000 đ,None,Việt Nam,Mới,Bảo hành hãng,VinFast,VF5,2026,Tự động,Điện,None,None,None,None,None,4,None

In [4]:
df_chotot = data_chotot.copy()

In [5]:
df_chotot.columns

Index(['name', 'price', 'Số_Km_đã_đi', 'Xuất_xứ', 'Tình_trạng',
       'Chính_sách_bảo_hành', 'Hãng', 'Dòng_xe', 'Năm_sản_xuất', 'Hộp_số',
       'Nhiên_liệu', 'Trọng_lượng', 'Trọng_tải', 'Số_đời_chủ',
       'Có_phụ_kiện_đi_kèm', 'Còn_hạn_đăng_kiểm', 'Số_chỗ', 'Kiểu_dáng'],
      dtype='object')

In [6]:
df_chotot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14690 entries, 0 to 14689
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 14690 non-null  object
 1   price                14690 non-null  object
 2   Số_Km_đã_đi          13245 non-null  object
 3   Xuất_xứ              14690 non-null  object
 4   Tình_trạng           14690 non-null  object
 5   Chính_sách_bảo_hành  14690 non-null  object
 6   Hãng                 14690 non-null  object
 7   Dòng_xe              14690 non-null  object
 8   Năm_sản_xuất         14690 non-null  object
 9   Hộp_số               14690 non-null  object
 10  Nhiên_liệu           14690 non-null  object
 11  Trọng_lượng          13396 non-null  object
 12  Trọng_tải            13396 non-null  object
 13  Số_đời_chủ           6578 non-null   object
 14  Có_phụ_kiện_đi_kèm   6318 non-null   object
 15  Còn_hạn_đăng_kiểm    6837 non-null   object
 16  Số_chỗ               11916 non-null  object
 17  Kiểu_dáng            9805 non-null   object
dtypes: object(18)
memory usage: 2.0+ MB

In [7]:
df_chotot = df_chotot[["Số_Km_đã_đi", "Tình_trạng", "Xuất_xứ", "Kiểu_dáng", "Nhiên_liệu", "name", "price", "Hãng", "Năm_sản_xuất", "Hộp_số"]].copy()

In [8]:
df_chotot.columns = ["km", "Tình_trạng", "origin", "body", "fuel", "name", "price", "brand", "age", "gearbox"]

In [9]:
df_chotot.describe(include='all').T

,count,unique,top,freq
km,13245,1794,100000,450
Tình_trạng,14690,2,Đã sử dụng,13396
origin,14690,11,Việt Nam,5043
body,9805,9,SUV / Cross over,3846
fuel,14690,4,Xăng,11044
name,14690,14246,Cần tìm mua ô tô cũ - hoa Hồng cho ng giới thiệu,6
price,14690,1501,450.000.000 đ,100
brand,14690,69,Toyota,2924
age,14690,45,2022,1502
gearbox,14690,5,Tự động,11472

In [10]:
df_chotot.isna().sum()

km            1445
Tình_trạng       0
origin           0
body          4885
fuel             0
name             0
price            0
brand            0
age              0
gearbox          0
dtype: int64

1.name

In [11]:
def clean_name(text):
    if not isinstance(text, str):
        return None
    
    text = re.sub(r"^\s*Xe\s+", "", text, flags=re.IGNORECASE)
    
    text = re.sub(r"[^a-zA-Z0-9À-ỹ\s]", " ", text)
    
    text = re.sub(r"\s+", " ", text)
    
    return text.strip()

In [12]:
df_chotot["name"] = df_chotot["name"].apply(clean_name)
df_chotot.sample(5)

,km,Tình_trạng,origin,body,fuel,name,price,brand,age,gearbox
8720,4539,Đã sử dụng,Đang cập nhật,Hatchback,Xăng,huyndai,315.000.000 đ,VinFast,2020,Tự động
7467,None,Mới,Trung Quốc,Sedan,Xăng,MG MG5 2024,325.000.000 đ,MG,2024,Số sàn
7137,None,Mới,Việt Nam,Sedan,Xăng,Toyota Vios Hỗ trợ 50 Thuế Trước Bạ,438.000.000 đ,Toyota,2025,Số sàn
7739,5000,Đã sử dụng,Nước khác,None,Động cơ Hybrid,Volvo S90L PLUS LWB ULTImate Recharge T8 Xăng ...,2.430.000.000 đ,Volvo,2024,Tự động
5064,55000,Đã sử dụng,Việt Nam,Minivan (MPV),Động cơ Hybrid,Kia Carnival 2022 2 2D Luxury 8 chỗ 55000 km,1.100.000.000 đ,Kia,2022,Tự động

2.price

In [13]:
df_chotot["price"].sample(5)

11123    130.000.000 đ
11485    749.000.000 đ
2178     668.000.000 đ
7310     440.000.000 đ
9698     190.000.000 đ
Name: price, dtype: object

In [14]:
df_chotot["price"] = (
    df_chotot["price"]
    .str.replace("đ", "", regex=False)
    .str.replace(".", "", regex=False)
    .str.strip()
    .astype(float)
    .astype("Int64")
)
df_chotot.price.sample(5)

6263      535000000
7686     1050000000
14251     482260000
6489      540000000
7354      340000000
Name: price, dtype: Int64

In [15]:
df_chotot["price"].isna().sum()

np.int64(0)

In [16]:
df_chotot = df_chotot[df_chotot["price"] > 50000000]

3.brand

In [17]:
df_chotot["brand"].sample(5)

7072      LandRover
13437         Honda
8885        Hyundai
12734    Mitsubishi
8366            Kia
Name: brand, dtype: object

In [18]:
df_chotot["brand"].isna().sum()

np.int64(0)

In [19]:
df_chotot["brand"].unique()

array(['Mitsubishi', 'Toyota', 'Mercedes Benz', 'Kia', 'Hyundai', 'Ford',
       'Dongfeng', 'Mazda', 'Peugeot', 'BMW', 'Audi', 'Honda', 'Nissan',
       'BYD', 'Chevrolet', 'Baic', 'Suzuki', 'MINI', 'Geely', 'Subaru',
       'Isuzu', 'Hãng khác', 'Ferrari', 'Daewoo', 'VinFast', 'Jeep',
       'Wuling', 'Asia', 'GMC', 'Lexus', 'MG', 'Skoda', 'Maserati',
       'Acura', 'Porsche', 'Chery', 'Volkswagen', 'LandRover',
       'Ssangyong', 'Cadillac', 'Daihatsu', 'Luxgen', 'Volvo', 'Jaguar',
       'RAM', 'Haima', 'Chrysler', 'Fiat', 'Citroen', 'Zotye', 'Proton',
       'GAC', 'Rolls Royce', 'Lynk&Co', 'Samsung', 'Gaz', 'Smart',
       'Changan', 'Opel', 'Mekong', 'Infiniti', 'Renault', 'Lamborghini',
       'UAZ', 'Bentley', 'SYM', 'Maybach'], dtype=object)

In [20]:
df_chotot["brand"] = df_chotot["brand"].str.lower()

4.year

In [21]:
df_chotot["age"].isna().sum()

np.int64(0)

In [22]:
df_chotot["age"] = pd.to_numeric(df_chotot["age"], errors="coerce")

In [23]:
df_chotot = df_chotot.dropna(subset=["age"])

In [24]:
df_chotot["age"] = 2026 - df_chotot["age"].astype(int)

In [25]:
df_chotot.sample(5)

,km,Tình_trạng,origin,body,fuel,name,price,brand,age,gearbox
2156,50000,Đã sử dụng,Đang cập nhật,Hatchback,Xăng,,399000000,mazda,6,Tự động
13134,40000,Đã sử dụng,Việt Nam,Minivan (MPV),Xăng,Hyundai Custin 2023 1 5Tubo Trắng 4 Vạn Tiêu C...,739000000,hyundai,3,Tự động
4105,155000,Đã sử dụng,Việt Nam,Sedan,Xăng,Bán Ford Laser siêu đẹp đời 2004 số tự động,115000000,ford,22,Tự động
10790,120000,Đã sử dụng,Việt Nam,None,Xăng,Toyota Fortuner 2012 AT 4x2,355000000,toyota,14,Tự động
2441,2700,Đã sử dụng,Việt Nam,SUV / Cross over,Xăng,Honda CR V 2025 L Trắng 2700km,1063000000,honda,1,Tự động

In [26]:
df_chotot["age"].isna().sum()

np.int64(0)

5.status

In [27]:
df_chotot["Tình_trạng"].unique()

array(['Đã sử dụng', 'Mới'], dtype=object)

In [28]:
df_chotot = df_chotot[df_chotot["Tình_trạng"] == "Đã sử dụng"]
df_chotot.drop(columns=["Tình_trạng"], inplace=True)

6.km

In [29]:
df_chotot["km"].head(5)

1     76018
3    220000
4     20000
5    110000
6     45000
Name: km, dtype: object

In [30]:
df_chotot["km"].isna().sum()

np.int64(146)

In [31]:
df_chotot["km"].describe()

count      12878
unique      1751
top       100000
freq         418
Name: km, dtype: object

In [32]:
df_chotot["km"] = pd.to_numeric(
    df_chotot["km"], errors="coerce"
).astype("Int64")

In [33]:
df_chotot = df_chotot[
    (df_chotot["km"] > 50) | (df_chotot["km"].isna())
]

In [34]:
df_chotot["km"].isna().sum()

np.int64(146)

In [35]:
df_chotot.head()

,km,origin,body,fuel,name,price,brand,age,gearbox
1,76018,Nước khác,None,Xăng,Mitsubishi Xpander Cross 2020 Trắng,475000000,mitsubishi,6,Tự động
3,220000,Đang cập nhật,None,Dầu,Toyota Fortuner Đen,400000000,toyota,15,Số sàn
4,20000,Việt Nam,Hatchback,Xăng,Mercedes Benz GLC 300 2023 Trắng 20 000 km,2250000000,mercedes benz,3,Tự động
5,110000,Việt Nam,None,Xăng,Kia Morning 2015 màu Kem bơ,175000000,kia,11,Tự động
6,45000,Đang cập nhật,None,Xăng,Hyundai Creta Đỏ 5 chỗ,529000000,hyundai,4,Tự động

7.origin

In [36]:
df_chotot["origin"].unique()

array(['Nước khác', 'Đang cập nhật', 'Việt Nam', 'Hàn Quốc', 'Thái Lan',
       'Đức', 'Đài Loan', 'Nhật Bản', 'Mỹ', 'Trung Quốc', 'Ấn Độ'],
      dtype=object)

In [37]:
df_chotot["origin"] = df_chotot["origin"].replace({
    "Việt Nam": "trong nước"
}).apply(lambda x: "nhập khẩu" if x not in ["trong nước"] else x)

In [38]:
df_chotot["origin"].value_counts()

origin
nhập khẩu     8704
trong nước    4103
Name: count, dtype: int64

8.body

In [39]:
df_chotot["body"].isna().sum()

np.int64(4243)

In [40]:
df_chotot["body"].unique()

array([None, 'Hatchback', 'Van', 'SUV / Cross over', 'Minivan (MPV)',
       'Pick-up (bán tải)', 'Sedan', 'Coupe (2 cửa)', 'Mui trần',
       'Kiểu dáng khác'], dtype=object)

In [41]:
df_chotot["body"] = df_chotot["body"].str.lower().str.strip()

9.fuel

In [42]:
df_chotot["fuel"].isna().sum()

np.int64(0)

In [43]:
df_chotot["fuel"].unique()

array(['Xăng', 'Dầu', 'Động cơ Hybrid', 'Điện'], dtype=object)

In [44]:
df_chotot["fuel"] = df_chotot["fuel"].apply(clean_fuel)

In [45]:
df_chotot["fuel"].unique()

array(['Xăng', 'Dầu', 'Hybrid', 'Điện'], dtype=object)

10.gearbox

In [46]:
df_chotot["gearbox"].isna().sum()

np.int64(0)

In [47]:
df_chotot["gearbox"].unique()

array(['Tự động', 'Số sàn', 'Bán tự động', '5', '4'], dtype=object)

In [48]:
def normalize_transmission(x):
    if pd.isna(x):
        return None
    
    x = str(x).strip().lower()
    
    if "tự động" in x:
        return "Số tự động"
    elif "sàn" in x:
        return "Số sàn"
    elif x.isdigit():
        return "Số sàn"
    else:
        return None

df_chotot["gearbox"] = df_chotot["gearbox"].apply(normalize_transmission)

In [49]:
df_chotot["gearbox"].unique()

array(['Số tự động', 'Số sàn'], dtype=object)

11.updata

In [50]:
df_chotot.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12807 entries, 1 to 14687
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   km       12661 non-null  Int64
 1   origin   12807 non-null  object
 2   body     8564 non-null   object
 3   fuel     12807 non-null  object
 4   name     12807 non-null  object
 5   price    12807 non-null  Int64
 6   brand    12807 non-null  object
 7   age      12807 non-null  int64
 8   gearbox  12807 non-null  object
dtypes: Int64(2), int64(1), object(6)
memory usage: 1.0+ MB

In [51]:
df_chotot.sample(10)

,km,origin,body,fuel,name,price,brand,age,gearbox
4101,45000,trong nước,suv / cross over,Xăng,Kia Seltos Trắng 5 chỗ preum Ban cao nhat,515000000,kia,5,Số tự động
8751,123000,nhập khẩu,None,Xăng,ford focus 2010 tự động bản cao cấp chính chủ,165000000,ford,16,Số tự động
2552,106000,trong nước,suv / cross over,Xăng,Chervolet Captiva Ltz 2 4AT 2010 đã bảo dưỡng ...,215000000,chevrolet,16,Số tự động
1456,98000,nhập khẩu,pick-up (bán tải),Dầu,FORD RANGER XLS 2019 AT 4X2 1 chủ Gia Lai,495000000,ford,7,Số tự động
2886,99000,trong nước,suv / cross over,Xăng,Ford escape 2013 chính chủ mình đứng tên,210000000,ford,13,Số tự động
13633,19000,nhập khẩu,None,Xăng,Ford Territory 2025 Titanium X 19 000 km,870000000,ford,1,Số tự động
1326,91000,nhập khẩu,None,Xăng,Kia Optima 2014 2 0AT 91000 km Trắng,370000000,kia,12,Số tự động
3187,11000,nhập khẩu,None,Xăng,Toyota Land Cruiser VX Đen,2650000000,toyota,10,Số tự động
13990,21500,nhập khẩu,None,Xăng,Lướt Volvo S90 Ultra 2025 Trắng 1 Chủ Máy B6,1999000000,volvo,1,Số tự động
6161,58000,trong nước,suv / cross over,Xăng,Toyota Innova 2018 Số sàn odo 5 8V km,415000000,toyota,8,Số sàn

In [52]:
upload_to_bigquery(df_chotot, table_id=table_id, if_exists="append" )

✅ Uploaded 12807 rows to khangtestdbt.xecupredict.data_merged

In [53]:
upload_to_db(df_chotot,table_name)

✅ Saved 12807 rows to PostgreSQL table 'data_merged'

In [54]:
#end