In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db
from clean_utils import *

In [2]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_cleaned"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [3]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.data_merged` """
data_merged = client.query(query).to_dataframe()
data_merged.head(1)

     km origin  body     gearbox  fuel           name      price brand  age
0  <NA>   None  None  Số tự động  Xăng  BMW 218i 2015  425000000   bmw   11

In [4]:
df = data_merged.copy()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25405 entries, 0 to 25404
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   km       25226 non-null  Int64
 1   origin   25372 non-null  object
 2   body     20920 non-null  object
 3   gearbox  25402 non-null  object
 4   fuel     25405 non-null  object
 5   name     25405 non-null  object
 6   price    25405 non-null  Int64
 7   brand    25405 non-null  object
 8   age      25405 non-null  Int64
dtypes: Int64(3), object(6)
memory usage: 1.8+ MB

In [6]:
df.duplicated().sum()

np.int64(1959)

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.isna().sum()

km          169
origin       23
body       4407
gearbox       2
fuel          0
name          0
price         0
brand         0
age           0
dtype: int64

1.brand

In [9]:
df["brand"].dtype

dtype('O')

In [10]:
df["brand"].unique()

array(['bmw', 'chevrolet', 'ford', 'honda', 'hyundai', 'kia', 'lexus',
       'mazda', 'mitsubishi', 'toyota', 'vinfast', 'acura', 'audi', 'byd',
       'bentley', 'cadillac', 'citroen', 'daewoo', 'ferrari', 'geely',
       'isuzu', 'jaguar', 'jeep', 'lamborghini', 'land', 'mg', 'mclaren',
       'mercedes-benz', 'mini', 'nissan', 'peugeot', 'porsche',
       'rolls-royce', 'suzuki', 'volkswagen', 'volvo', 'wuling',
       'mercedes benz', 'hãng khác', 'baic', 'gmc', 'landrover',
       'subaru', 'ssangyong', 'fiat', 'daihatsu', 'dongfeng', 'gac',
       'haima', 'infiniti', 'luxgen', 'maserati', 'mekong', 'renault',
       'rolls royce', 'sym', 'samsung', 'skoda', 'smart', 'changan',
       'opel', 'zotye', 'gaz', 'uaz', 'ram', 'chrysler', 'hongqi',
       'dodge', 'dongben', 'aston', 'kenbo', 'lincoln', 'mercedes',
       'rolls', 'scion', 'thaco', 'maybach', 'proton', 'lynk&co', 'asia'],
      dtype=object)

In [11]:
brand_alias = {
    "mercedes": "mercedes-benz",
    "mercedes benz": "mercedes-benz",

    "rolls": "rolls-royce",
    "rolls royce": "rolls-royce",

    "land": "land rover",
    "landrover": "land rover",

    "lynk": "lynk & co",
    "lynk&co": "lynk & co"
}

In [12]:
df["brand"] = df["brand"].replace(brand_alias)

top_brands = df["brand"].value_counts().nlargest(25).index
df["brand"] = df["brand"].apply(lambda x: x if x in top_brands else "other")

In [13]:
df["brand"].value_counts()

brand
toyota           4267
ford             2626
hyundai          2315
kia              2298
mercedes-benz    2071
mazda            1534
mitsubishi       1333
vinfast          1146
honda             976
lexus             696
bmw               600
chevrolet         553
suzuki            399
other             391
porsche           301
peugeot           298
mg                277
nissan            273
audi              272
land rover        230
volkswagen        157
volvo             112
isuzu             110
daewoo             97
mini               64
subaru             50
Name: count, dtype: int64

2.origin

In [14]:
df["origin"].unique()

array([None, 'nhập khẩu', 'trong nước'], dtype=object)

In [15]:
df["origin"].value_counts()

origin
nhập khẩu     13798
trong nước     9625
Name: count, dtype: int64

In [16]:
origin_mode_per_brand = df.groupby('brand')['origin'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
origin_mode_per_brand

brand
audi              nhập khẩu
bmw               nhập khẩu
chevrolet         nhập khẩu
daewoo            nhập khẩu
ford              nhập khẩu
honda             nhập khẩu
hyundai          trong nước
isuzu             nhập khẩu
kia              trong nước
land rover        nhập khẩu
lexus             nhập khẩu
mazda            trong nước
mercedes-benz    trong nước
mg                nhập khẩu
mini              nhập khẩu
mitsubishi        nhập khẩu
nissan            nhập khẩu
other             nhập khẩu
peugeot          trong nước
porsche           nhập khẩu
subaru            nhập khẩu
suzuki            nhập khẩu
toyota            nhập khẩu
vinfast          trong nước
volkswagen        nhập khẩu
volvo             nhập khẩu
Name: origin, dtype: object

In [17]:
df['origin'] = df.apply(
    lambda row: origin_mode_per_brand[row['brand']] if pd.isna(row['origin']) else row['origin'],
    axis=1
)

In [18]:
df['origin'].isna().sum()

np.int64(0)

3.body

In [19]:
df["body"].unique()

array([None, 'sedan', 'bán tải', 'suv', 'hatchback', 'coupe', 'sport car',
       'convertible', 'van/minivan', 'crossover', 'mpv', 'minibus',
       'xe tải', 'mui trần', 'coupe (2 cửa)', 'kiểu dáng khác',
       'minivan (mpv)', 'pick-up (bán tải)', 'truck',
       'bán tải / pickup', 'convertible/cabriolet', 'wagon',
       'suv / cross over', 'van'], dtype=object)

In [20]:
df['body'] = df['body'].replace({
    'xe tải': 'truck',
    'truck': 'truck',
    'bán tải': 'pickup',
    'bán tải / pickup': 'pickup',
    'pick-up (bán tải)': 'pickup',
    'van/minivan': 'minivan',
    'minivan (mpv)': 'minivan',
    'mpv': 'minivan',
    'suv / cross over': 'suv',
    'crossover': 'suv',
    'convertible/cabriolet': 'convertible',
    'coupe (2 cửa)': 'coupe'
})

In [21]:
body_mode_per_brand = df.groupby('brand')['body'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)
body_mode_per_brand

brand
audi                   suv
bmw                  sedan
chevrolet            sedan
daewoo               sedan
ford                   suv
honda                  suv
hyundai                suv
isuzu               pickup
kia                    suv
land rover             suv
lexus                  suv
mazda                  suv
mercedes-benz        sedan
mg                     suv
mini             hatchback
mitsubishi             suv
nissan              pickup
other                  suv
peugeot                suv
porsche                suv
subaru                 suv
suzuki                 suv
toyota                 suv
vinfast                suv
volkswagen             suv
volvo                  suv
Name: body, dtype: object

In [22]:
df['body'] = df.apply(
    lambda row: body_mode_per_brand[row['brand']] if pd.isna(row['body']) else row['body'],
    axis=1
)

In [23]:
df['body'].isna().sum()

np.int64(0)

4.fuel

In [24]:
df["fuel"].unique()

array(['Xăng', 'Dầu', 'Điện', 'Hybrid'], dtype=object)

In [25]:
df['fuel'] = df['fuel'].str.lower()

In [26]:
df['fuel'].isna().sum()

np.int64(0)

5.gearbox

In [27]:
df["gearbox"].isna().sum()

np.int64(2)

In [28]:
df["gearbox"] = df["gearbox"].fillna(
    df.groupby("brand")["gearbox"].transform(lambda x: x.mode()[0] if not x.mode().empty else None)
)

In [29]:
df["gearbox"].isna().sum()

np.int64(0)

6.km

In [30]:
df["km"].isna().sum()

np.int64(169)

In [31]:
df["km"] = df["km"].astype(float)

df["km"] = df["km"].fillna(
    df.groupby("age")["km"].transform("mean")
)

In [32]:
df["km"].isna().sum()

np.int64(0)

7.outlier

In [33]:
df["price"] = df["price"].astype(float)
df["km"] = df["km"].astype(float)
df["age"] = df["age"].astype(float)

In [34]:
def cap_outliers_group(df, column, group_cols):
    def cap_group(x):
        Q1 = x[column].quantile(0.25)
        Q3 = x[column].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        return x[column].clip(lower, upper)
    
    df[column] = df.groupby(group_cols, group_keys=False).apply(cap_group)
    return df

In [35]:
df = cap_outliers_group(df, "km", ['age'])
df = cap_outliers_group(df, "price", ['brand','age'])

In [36]:
df.head()

,km,origin,body,gearbox,fuel,name,price,brand,age
0,100057.995475,nhập khẩu,sedan,Số tự động,xăng,BMW 218i 2015,4.250000e+08,bmw,11.0
2,93759.138627,nhập khẩu,sedan,Số tự động,xăng,Chevrolet Aveo 2018,1.500000e+08,chevrolet,8.0
4,21000.000000,nhập khẩu,suv,Số tự động,xăng,Ford Everest 2024,1.390000e+09,ford,2.0
6,103803.917402,nhập khẩu,pickup,Số tự động,xăng,Ford Ranger 2016,3.850000e+08,ford,10.0
8,90000.000000,nhập khẩu,suv,Số tự động,xăng,Honda CR-V 2018,6.900000e+08,honda,8.0

In [37]:
df.drop(columns=["name"], inplace=True)

In [38]:
X = df.drop(columns=["price"])
X.head()

              km     origin    body     gearbox  fuel      brand   age
0  100057.995475  nhập khẩu   sedan  Số tự động  xăng        bmw  11.0
2   93759.138627  nhập khẩu   sedan  Số tự động  xăng  chevrolet   8.0
4   21000.000000  nhập khẩu     suv  Số tự động  xăng       ford   2.0
6  103803.917402  nhập khẩu  pickup  Số tự động  xăng       ford  10.0
8   90000.000000  nhập khẩu     suv  Số tự động  xăng      honda   8.0

In [39]:
X[X.duplicated(keep=False)]

,km,origin,body,gearbox,fuel,brand,age
0,100057.995475,nhập khẩu,sedan,Số tự động,xăng,bmw,11.0
4,21000.000000,nhập khẩu,suv,Số tự động,xăng,ford,2.0
8,90000.000000,nhập khẩu,suv,Số tự động,xăng,honda,8.0
20,120131.397196,trong nước,hatchback,Số tự động,xăng,kia,15.0
26,80000.000000,nhập khẩu,suv,Số tự động,xăng,mitsubishi,9.0
...,...,...,...,...,...,...,...
25364,152500.000000,trong nước,van,Số sàn,dầu,ford,7.0
25382,191152.500000,trong nước,van,Số sàn,dầu,ford,11.0
25383,16500.000000,nhập khẩu,van,Số sàn,dầu,ford,6.0
25386,20000.000000,nhập khẩu,van,Số tự động,xăng,volkswagen,2.0
25388,20000.000000,nhập khẩu,van,Số tự động,xăng,volkswagen,2.0

In [40]:
df_unique = df.groupby(list(X.columns), as_index=False)["price"].mean()
df_unique

,km,origin,body,gearbox,fuel,brand,age,price
0,51.0,trong nước,suv,Số tự động,điện,vinfast,2.0,4.100000e+08
1,52.0,nhập khẩu,sedan,Số tự động,xăng,mercedes-benz,3.0,2.429000e+09
2,55.0,nhập khẩu,sedan,Số tự động,xăng,bmw,20.0,1.650000e+08
3,55.0,trong nước,suv,Số tự động,xăng,mazda,4.0,7.950000e+08
4,56.0,nhập khẩu,coupe,Số tự động,xăng,mini,20.0,3.000000e+08
...,...,...,...,...,...,...,...,...
16791,450000.0,nhập khẩu,sedan,Số tự động,xăng,toyota,31.0,7.500000e+07
16792,456321.0,nhập khẩu,pickup,Số sàn,xăng,isuzu,29.0,7.900000e+07
16793,500000.0,trong nước,pickup,Số sàn,xăng,nissan,42.0,8.567000e+07
16794,686868.0,nhập khẩu,suv,Số sàn,dầu,toyota,36.0,3.525000e+08
16795,789789.0,nhập khẩu,sedan,Số sàn,xăng,nissan,36.0,5.500000e+07

In [41]:
cols_show = ["brand", "body", "fuel", "origin"]

df_unique[cols_show] = df_unique[cols_show].apply(lambda c: c.str.title())

In [42]:
df_unique.sample(10)

,km,origin,body,gearbox,fuel,brand,age,price
3517,26000.0,Nhập Khẩu,Sedan,Số sàn,Xăng,Chevrolet,8.0,1.860000e+08
16466,203000.0,Nhập Khẩu,Suv,Số tự động,Xăng,Lexus,16.0,1.599000e+09
10418,80000.0,Trong Nước,Sedan,Số tự động,Xăng,Chevrolet,9.0,2.800000e+08
15725,157000.0,Trong Nước,Hatchback,Số tự động,Xăng,Hyundai,8.0,2.900000e+08
15645,153000.0,Nhập Khẩu,Sedan,Số tự động,Xăng,Chevrolet,17.0,1.650000e+08
3585,26000.0,Trong Nước,Suv,Số tự động,Xăng,Hyundai,4.0,1.092500e+09
1099,7000.0,Trong Nước,Suv,Số tự động,Xăng,Toyota,1.0,8.480000e+08
8462,66000.0,Nhập Khẩu,Mui Trần,Số tự động,Xăng,Audi,18.0,6.390000e+08
11728,90000.0,Trong Nước,Suv,Số tự động,Xăng,Honda,11.0,4.625000e+08
2996,20500.0,Trong Nước,Suv,Số tự động,Xăng,Toyota,3.0,5.200000e+08

In [43]:
df_unique.duplicated().sum()

np.int64(0)

In [44]:
import json

unique_values = {
    'origin':  df_unique['origin'].value_counts().index.tolist(),
    'fuel':    df_unique['fuel'].value_counts().index.tolist(),
    'body':    df_unique['body'].value_counts().index.tolist(),
    'brand':   df_unique['brand'].value_counts().index.tolist(),
    'gearbox': df_unique['gearbox'].value_counts().index.tolist(),  
}

with open('../../model/unique_values.json', 'w', encoding='utf-8') as f:
    json.dump(unique_values, f, ensure_ascii=False, indent=2)

In [45]:
upload_to_bigquery(df_unique, table_id=table_id, if_exists="replace" )

✅ Uploaded 16796 rows to khangtestdbt.xecupredict.data_cleaned

In [46]:
upload_to_db(df_unique,table_name)

✅ Saved 16796 rows to PostgreSQL table 'data_cleaned'

# end