In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery,upload_to_db

In [2]:
import pandas as pd
import numpy as np

In [3]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)
table_name ="data_train_model"
table_id = f"{GCS_PROJECT_ID}.{GCS_BUCKET_NAME}.{table_name}"

In [4]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.data_cleaned` """
data = client.query(query).to_dataframe()
data.head(1)

     km      origin body     gearbox  fuel    brand  age        price
0  51.0  Trong Nước  Suv  Số tự động  Điện  Vinfast  2.0  410000000.0

In [5]:
df = data.copy()

In [6]:
df.shape

(16796, 8)

In [7]:
df.head(5)

,km,origin,body,gearbox,fuel,brand,age,price
0,51.0,Trong Nước,Suv,Số tự động,Điện,Vinfast,2.0,4.100000e+08
1,52.0,Nhập Khẩu,Sedan,Số tự động,Xăng,Mercedes-Benz,3.0,2.429000e+09
2,55.0,Nhập Khẩu,Sedan,Số tự động,Xăng,Bmw,20.0,1.650000e+08
3,55.0,Trong Nước,Suv,Số tự động,Xăng,Mazda,4.0,7.950000e+08
4,56.0,Nhập Khẩu,Coupe,Số tự động,Xăng,Mini,20.0,3.000000e+08

In [8]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[-1, 5, 10, 15, 100],
    labels=["New", "Young", "Mid", "Old"]
)

In [9]:
df["km_per_year"] = df["km"] / (df["age"] + 1)

df["log_age"] = np.log1p(df["age"])

top_body = df["body"].value_counts().nlargest(5).index
df["body_group"] = df["body"].where(df["body"].isin(top_body), "Other")

In [10]:
top_brand = df["brand"].value_counts().nlargest(10).index
df["brand_group"] = df["brand"].where(df["brand"].isin(top_brand), "Other")

In [11]:
df["is_imported"] = (df["origin"] == "Nhập Khẩu").astype(object)

df["imported_age"] = df["is_imported"].astype(str) + "_" + df["age_group"].astype(str)

In [12]:
df.head()

,km,origin,body,gearbox,fuel,brand,age,price,age_group,km_per_year,log_age,body_group,brand_group,is_imported,imported_age
0,51.0,Trong Nước,Suv,Số tự động,Điện,Vinfast,2.0,4.100000e+08,New,17.000000,1.098612,Suv,Vinfast,False,False_New
1,52.0,Nhập Khẩu,Sedan,Số tự động,Xăng,Mercedes-Benz,3.0,2.429000e+09,New,13.000000,1.386294,Sedan,Mercedes-Benz,True,True_New
2,55.0,Nhập Khẩu,Sedan,Số tự động,Xăng,Bmw,20.0,1.650000e+08,Old,2.619048,3.044522,Sedan,Other,True,True_Old
3,55.0,Trong Nước,Suv,Số tự động,Xăng,Mazda,4.0,7.950000e+08,New,11.000000,1.609438,Suv,Mazda,False,False_New
4,56.0,Nhập Khẩu,Coupe,Số tự động,Xăng,Mini,20.0,3.000000e+08,Old,2.666667,3.044522,Other,Other,True,True_Old

In [13]:
X = df.drop(columns=["price"])
X_ = df[["price"]]

In [14]:
X.duplicated().sum()

np.int64(0)

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16796 entries, 0 to 16795
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   km            16796 non-null  float64
 1   origin        16796 non-null  object
 2   body          16796 non-null  object
 3   gearbox       16796 non-null  object
 4   fuel          16796 non-null  object
 5   brand         16796 non-null  object
 6   age           16796 non-null  float64
 7   age_group     16796 non-null  category
 8   km_per_year   16796 non-null  float64
 9   log_age       16796 non-null  float64
 10  body_group    16796 non-null  object
 11  brand_group   16796 non-null  object
 12  is_imported   16796 non-null  object
 13  imported_age  16796 non-null  object
dtypes: category(1), float64(4), object(9)
memory usage: 1.7+ MB

In [16]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler

categorical_cols = [col for col in X.columns 
                    if X[col].dtype in ['object','category'] and col not in X_]
numerical_cols = [col for col in X.columns 
                  if X[col].dtype in ['float64'] and col not in X_]

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_cat = ohe.fit_transform(X[categorical_cols])
cat_feature_names = ohe.get_feature_names_out(categorical_cols)
X_cat_df = pd.DataFrame(X_cat, columns=cat_feature_names, index=X.index)


scaler = StandardScaler()
X_num = scaler.fit_transform(X[numerical_cols])
X_num_df = pd.DataFrame(X_num, columns=numerical_cols, index=X.index)

X_encoded = pd.concat([X_num_df, X_cat_df, X_], axis=1)
X_encoded.shape

(16796, 84)

In [17]:
X_encoded.head()

,km,age,km_per_year,log_age,origin_Nhập Khẩu,origin_Trong Nước,body_Convertible,body_Coupe,body_Hatchback,body_Kiểu Dáng Khác,...,is_imported_True,imported_age_False_Mid,imported_age_False_New,imported_age_False_Old,imported_age_False_Young,imported_age_True_Mid,imported_age_True_New,imported_age_True_Old,imported_age_True_Young,price
0,-1.348089,-1.086785,-1.789765,-1.490741,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.100000e+08
1,-1.348071,-0.910339,-1.790627,-1.029608,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.429000e+09
2,-1.348014,2.089234,-1.792866,1.628410,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.650000e+08
3,-1.348014,-0.733894,-1.791059,-0.671925,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,7.950000e+08
4,-1.347996,2.089234,-1.792856,1.628410,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.000000e+08

In [ ]:
from joblib import dump

dump(ohe, "../../model/onehot_encoder.pkl")
dump(scaler,"../../model/scaler.pkl")

['../../model/scaler.pkl']

In [19]:
upload_to_bigquery(X_encoded, table_id=table_id, if_exists="replace" )

✅ Uploaded 16796 rows to khangtestdbt.xecupredict.data_train_model

In [20]:
upload_to_db(X_encoded,table_name)

✅ Saved 16796 rows to PostgreSQL table 'data_train_model'

# end