In [1]:
import warnings
warnings.filterwarnings("ignore")
import sys, os
sys.path.append(os.path.abspath("../.."))
from configs import GOOGLE_APPLICATION_CREDENTIALS,GCS_BUCKET_NAME,GCS_PROJECT_ID
from google.cloud import bigquery
from src.utils.io_utils import upload_to_bigquery

In [2]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error, root_mean_squared_error, mean_absolute_error
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [3]:
client = bigquery.Client.from_service_account_json(GOOGLE_APPLICATION_CREDENTIALS)

In [4]:
query = """SELECT *
FROM `khangtestdbt.xecupredict.data_train_model` """
data = client.query(query).to_dataframe()
data.head(1)

,km,age,km_per_year,log_age,origin_Nhập Khẩu,origin_Trong Nước,body_Convertible,body_Coupe,body_Hatchback,body_Kiểu Dáng Khác,...,is_imported_True,imported_age_False_Mid,imported_age_False_New,imported_age_False_Old,imported_age_False_Young,imported_age_True_Mid,imported_age_True_New,imported_age_True_Old,imported_age_True_Young,price
0,-1.348089,-1.086785,-1.789765,-1.490741,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,410000000.0

In [5]:
df = data.copy()

In [6]:
df.shape

(16796, 84)

In [7]:
X = df.drop(columns=["price"])
y = np.log(df["price"])

In [8]:
np.random.seed(42)

X_train, X_test, y_train, y_test =  train_test_split(X,
                                                     y,
                                                     test_size=0.2)

In [9]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(),

    "Decision Tree": DecisionTreeRegressor(),

    "SVR": SVR(),
}

In [10]:
rows = []  

for name, model in models.items():
    model.fit(X_train, y_train)

    train_pred = model.predict(X_train)
    test_pred  = model.predict(X_test)

    r2_train = r2_score(y_train, train_pred)
    r2_test  = r2_score(y_test, test_pred)

    # MSE
    mse_train = mean_squared_error(y_train, train_pred)
    mse_test  = mean_squared_error(y_test, test_pred)

    # RMSE
    rmse_train = root_mean_squared_error(y_train, train_pred)
    rmse_test  = root_mean_squared_error(y_test, test_pred)

    # MAE
    mae_train = mean_absolute_error(y_train, train_pred)
    mae_test  = mean_absolute_error(y_test, test_pred)

    rows.append([
        name,
        r2_train, r2_test,
        rmse_train, rmse_test,
        mse_train, mse_test,
        mae_train, mae_test
    ])

df_results = pd.DataFrame(
    rows,
    columns=[
        "Model",
        "R2_Train", "R2_Test",
        "RMSE_Train", "RMSE_Test",
        "MSE_Train", "MSE_Test",
        "MAE_Train", "MAE_Test"
    ]
)

df_results

,Model,R2_Train,R2_Test,RMSE_Train,RMSE_Test,MSE_Train,MSE_Test,MAE_Train,MAE_Test
0,Linear Regression,0.786885,0.785004,3.890318e-01,0.389941,1.513458e-01,0.152054,2.716225e-01,0.272326
1,Ridge Regression,0.786867,0.784972,3.890480e-01,0.389969,1.513584e-01,0.152076,2.716984e-01,0.272471
2,Decision Tree,1.000000,0.786347,9.194888e-17,0.388721,8.454597e-33,0.151104,2.379758e-18,0.240867
3,SVR,0.887863,0.872522,2.821976e-01,0.300262,7.963548e-02,0.090157,1.820599e-01,0.193982

In [11]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

svr_param_grid = {
    'kernel': ['rbf', 'linear'],
    'C': [0.1, 1, 10],
    'epsilon': [0.01, 0.1, 0.5]
}

svr_grid = GridSearchCV(
    SVR(),
    param_grid=svr_param_grid,
    scoring='neg_mean_squared_error',
    cv=3,
    n_jobs=-1,
    verbose=1
)

svr_grid.fit(X_train, y_train)
svr_best = svr_grid.best_estimator_

y_tr_pred = svr_best.predict(X_train)
y_te_pred = svr_best.predict(X_test)

print("==== SVR ====")
print("Best params:", svr_grid.best_params_)

Fitting 3 folds for each of 18 candidates, totalling 54 fits
==== SVR ====
Best params: {'C': 10, 'epsilon': 0.1, 'kernel': 'rbf'}

In [12]:
print("==== SVR ====")
print("Best params:", svr_grid.best_params_)
print("R2 Train:", r2_score(y_train, y_tr_pred))
print("R2 Test :", r2_score(y_test, y_te_pred))
print("RMSE Train:", np.sqrt(mean_squared_error(y_train, y_tr_pred)))
print("RMSE Test :", np.sqrt(mean_squared_error(y_test, y_te_pred)))
print("MSE Train:", mean_squared_error(y_train, y_tr_pred))
print("MSE Test :", mean_squared_error(y_test, y_te_pred))
print("MAE Train:", mean_absolute_error(y_train, y_tr_pred))
print("MAE Test :", mean_absolute_error(y_test, y_te_pred))

==== SVR ====
Best params: {'C': 10, 'epsilon': 0.1, 'kernel': 'rbf'}
R2 Train: 0.9103321518162638
R2 Test : 0.8709471418944923
RMSE Train: 0.2523461066380292
RMSE Test : 0.30211113849458504
MSE Train: 0.0636785575353716
MSE Test : 0.09127114000249434
MAE Train: 0.16198527906306673
MAE Test : 0.1917455779216838

In [13]:
round(np.exp(0.1917)-1,2)

np.float64(0.21)

In [14]:
round(np.exp(0.1619)-1,2)

np.float64(0.18)

* save model

In [15]:
import joblib

joblib.dump(svr_best, "../../model/svr_best.joblib")

['../../model/svr_best.joblib']

In [16]:
# end